global:
  domain: argocd.home.norriswu.me

configs:
  params:
    server.insecure: true
  cm:
    admin.enabled: false
    dex.config: |
      connectors:
      - config:
          issuer: https://authentik.home.norriswu.me/application/o/argocd/
          clientID: $argocd-oauth-client:client-id
          clientSecret: $argocd-oauth-client:client-secret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
        name: authentik
        type: oidc
        id: authentik
  rbac:
    policy.csv: |
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    extraTls:
      - hosts:
          - argocd.home.norriswu.me
