clusterName: teleport.norriswu.me
proxyListenerMode: multiplex
priorityClassName: system-cluster-critical

service:
  spec:
    loadBalancerClass: tailscale
annotations:
  service:
    tailscale.com/hostname: teleport

tls:
  existingSecretName: "teleport-certificate-secret"

authentication:
  type: github
