apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: nori-cloud
  labels:
    app: radicale
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs
  resources:
    requests:
      storage: 1Gi
