apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: outpost-secret
    namespace: nori-cloud
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: infisical-nori-cloud
        kind: SecretStore
    target:
        name: outpost-secret
        creationPolicy: Owner
    data:
        - secretKey: AUTHENTIK_CLIENT_ID
          remoteRef:
              key: /outpost/AUTHENTIK_CLIENT_ID
        - secretKey: AUTHENTIK_CLIENT_SECRET
          remoteRef:
              key: /outpost/AUTHENTIK_CLIENT_SECRET
        - secretKey: AUTHENTIK_DISCOVERY_URL
          remoteRef:
              key: /outpost/AUTHENTIK_DISCOVERY_URL
        - secretKey: BETTER_AUTH_SECRET
          remoteRef:
              key: /outpost/BETTER_AUTH_SECRET
        - secretKey: BETTER_AUTH_URL
          remoteRef:
              key: /outpost/BETTER_AUTH_URL
        - secretKey: DATABASE_URL
          remoteRef:
              key: /outpost/DATABASE_URL
        - secretKey: DEEPSEEK_API_KEY
          remoteRef:
              key: /outpost/DEEPSEEK_API_KEY
        - secretKey: NEXT_PUBLIC_BETTER_AUTH_URL
          remoteRef:
              key: /outpost/NEXT_PUBLIC_BETTER_AUTH_URL
        - secretKey: NODE_ENV
          remoteRef:
              key: /outpost/NODE_ENV
        - secretKey: PROFILER_CONTEXT_URLS
          remoteRef:
              key: /outpost/PROFILER_CONTEXT_URLS
