apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outpost-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: outpost-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /outpost
