# prettier-ignore
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: {{ $.Release.Namespace | quote }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  dataFrom:
    - find:
        name:
          regexp: AUTHENTIK_*
