apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-auth
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: infisical-nori-cloud-auth
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: INFISICAL_MI_UA_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: INFISICAL_MI_UA_CLIENT_SECRET
