apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-nori-cloud
  namespace: nori-cloud
spec:
  provider:
    infisical:
      hostAPI: https://infisical.home.norriswu.me
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-nori-cloud-auth
            namespace: nori-cloud
            key: clientId
          clientSecret:
            name: infisical-nori-cloud-auth
            namespace: nori-cloud
            key: clientSecret
      secretsScope:
        projectSlug: nori-cloud-apps-vi-m1
        environmentSlug: prod
        secretsPath: /
        recursive: true
