apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nori-cloud-appset
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          - app: cloudbeaver
          - app: cloudflare-tunnel
          - app: ghcr-credentials
          - app: guppy
          - app: infisical-secretstore
          - app: postgres
          - app: actual-budget
          - app: kokoro
          - app: whisper
          - app: open-webui
          - app: story
  template:
    metadata:
      name: "{{app}}"
    spec:
      project: default
      source:
        path: "apps/{{app}}"
        repoURL: "https://github.com/nori-cloud/lab.git"
        targetRevision: HEAD
      destination:
        namespace: nori-cloud
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
