apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: nori-cloud-appset
    namespace: argo-cd
spec:
    generators:
        - list:
              elements:
                  - app: cloudflare-tunnel
                  - app: ghcr-credentials
                  - app: infisical-secretstore
                  - app: pgadmin
                  - app: postgres
                  - app: valkey
                  - app: actual-budget
                  - app: affine
                  - app: outpost
                  - app: koukou
                  - app: boubou
                  - app: nats
                  - app: radicale

    template:
        metadata:
            name: '{{app}}'
        spec:
            project: default
            source:
                path: 'apps/{{app}}'
                repoURL: 'https://github.com/nori-cloud/lab.git'
                targetRevision: HEAD
            destination:
                namespace: nori-cloud
                server: 'https://kubernetes.default.svc'
            syncPolicy:
                automated:
                    prune: true
                    selfHeal: true
