apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nori-cloud-staging
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          - app: staging-certificate
          - app: staging-secretstore
          - app: guppy
          - app: story
  template:
    metadata:
      name: "{{app}}-staging"
    spec:
      project: default
      source:
        path: "apps/staging/{{app}}"
        repoURL: "https://github.com/nori-cloud/lab.git"
        targetRevision: HEAD
      destination:
        namespace: nori-cloud
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
