apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: nori-cloud
  labels:
    app: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: ghcr.io/stirling-tools/stirling-pdf:2.14.2-ultra-lite
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
