apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: nori-cloud
  labels:
    app: stirling-pdf
spec:
  type: ClusterIP
  selector:
    app: stirling-pdf
  ports:
    - port: 8080
      targetPort: 8080
      name: http
