global:
    domain: argocd.home.norriswu.me
    priorityClassName: system-cluster-critical

configs:
    params:
        server.insecure: true
    cm:
        admin.enabled: false
        dex.config: |
            connectors:
            - config:
                issuer: $argocd-oauth-client:ARGOCD_OAUTH_CLIENT_ISSUER
                clientID: $argocd-oauth-client:ARGOCD_OAUTH_CLIENT_ID
                clientSecret: $argocd-oauth-client:ARGOCD_OAUTH_CLIENT_SECRET
                insecureEnableGroups: true
                scopes:
                  - openid
                  - profile
                  - email
              name: authentik
              type: oidc
              id: authentik
    rbac:
        policy.csv: |
            g, ArgoCD Admins, role:admin
            g, ArgoCD Viewers, role:readonly

server:
    ingress:
        enabled: true
        ingressClassName: traefik
        extraHosts:
            - name: argocd.norriswu.me
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack

repoServer:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack

controller:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack

dex:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack

redis:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack

notifications:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack

applicationSet:
    allowAnyNamespace: true
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack
