apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: story-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: story-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: STORY_*
