apiVersion: apps/v1
kind: Deployment
metadata:
  name: vesta
  namespace: nori-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vesta
  template:
    metadata:
      labels:
        app: vesta
    spec:
      containers:
        - image: ghcr.io/nori-cloud/vesta:6c735a5
          name: vesta
          envFrom:
            - secretRef:
                name: vesta-secret
          ports:
            - containerPort: 3000
