apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: vesta-secret
    namespace: nori-cloud
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: infisical-nori-cloud
        kind: SecretStore
    target:
        name: vesta-secret
        creationPolicy: Owner
    dataFrom:
        - find:
              name:
                  regexp: VESTA_*
