apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudbeaver-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: cloudbeaver-secret
    creationPolicy: Owner
  data:
    - secretKey: CB_ADMIN_NAME
      remoteRef:
        key: /cloudbeaver/CB_ADMIN_NAME
    - secretKey: CB_ADMIN_PASSWORD
      remoteRef:
        key: /cloudbeaver/CB_ADMIN_PASSWORD
