apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: nori-cloud
  labels:
    app: openclaw
data:
  openclaw.json: |
    {
      "gateway": {
        "bind": "lan",
        "auth": {
          "mode": "trusted-proxy",
          "trustedProxy": {
            "userHeader": "X-forwarded-user"
          }
        },
        "trustedProxies": ["10.0.0.0/8"]
      }
    }
