apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: openclaw-secret
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: /openclaw/OPENCLAW_ANTHROPIC_API_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: /openclaw/OPENCLAW_DATABASE_URL
