apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw
  namespace: nori-cloud
  labels:
    app: openclaw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openclaw.norriswu.me`)
      kind: Rule
      services:
        - name: openclaw
          port: 18789
      middlewares:
        - name: authentik
