# https://github.com/fenio/k8s-truenas?tab=readme-ov-file#iscsiyaml
csiDriver:
    name: 'iscsi'
storageClasses:
    - name: iscsi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: 'false'
      mountOptions: []
      secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
volumeSnapshotClasses:
    - name: iscsi
      parameters:
          detachedSnapshots: 'true'

driver:
    # Driver config is stored in a Kubernetes secret
    # Create the secret using: ./setup-democratic-csi-secret.sh
    existingConfigSecret: democratic-csi-driver-config
    config:
        driver: freenas-iscsi
