apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook-ui
  namespace: nori-butler
  labels:
    app: guestbook-ui
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`guestbook-ui.norriswu.me`)
      kind: Rule
      services:
        - name: guestbook-ui
          port: 80
