services:
  web:
    image: githubyumao/mcsmanager-web:latest
    ports:
      - "23333:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mcsmanager_web_data:/opt/mcsmanager/web/data
      - mcsmanager_web_logs:/opt/mcsmanager/web/logs

  daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    ports:
      - "24444:24444"
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=mcsmanager_data/daemon/data/InstanceData
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mcsmanager_daemon_data:/opt/mcsmanager/daemon/data
      - mcsmanager_daemon_logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mcsmanager_web_data:
  mcsmanager_web_logs:
  mcsmanager_daemon_data:
  mcsmanager_daemon_logs:
