apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-budget-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: actual-budget-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /actual-budget
        name:
          regexp: "^ACTUAL_OPENID_.*"
