# prettier-ignore
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    name: infisical
    namespace: {{ $.Release.Namespace | quote }}
spec:
    provider:
        infisical:
            hostAPI: {{ .Values.infisical.host | quote }}
            auth:
                universalAuthCredentials:
                    clientId:
                        name: infisical-universal-auth
                        namespace: external-secrets
                        key: client_id
                    clientSecret:
                        name: infisical-universal-auth
                        namespace: external-secrets
                        key: client_secret
            secretsScope:
                projectSlug: {{ .Values.infisical.projectSlug | quote }}
                environmentSlug: {{ .Values.infisical.environment | quote }}
                secretsPath: {{ .Values.infisical.secretsPath | quote }}
                recursive: {{ .Values.infisical.recursive }}
