apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine
  namespace: nori-cloud
  labels:
    app: affine
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
    spec:
      containers:
        - name: affine
          image: ghcr.io/toeverything/affine-self-hosted:latest
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: affine-data
