apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: affine-secret
    creationPolicy: Owner
  data:
    # database credentials
    - secretKey: DB_USERNAME
      remoteRef:
        key: /affine/AFFINE_DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /affine/AFFINE_DB_PASSWORD
    - secretKey: DB_DATABASE
      remoteRef:
        key: /affine/AFFINE_DB_DATABASE
    - secretKey: DATABASE_URL
      remoteRef:
        key: /affine/AFFINE_DATABASE_URL
    # server config
    - secretKey: AFFINE_SERVER_HTTPS
      remoteRef:
        key: /affine/AFFINE_SERVER_HTTPS
    - secretKey: AFFINE_SERVER_EXTERNAL_URL
      remoteRef:
        key: /affine/AFFINE_SERVER_EXTERNAL_URL
    # redis config
    - secretKey: REDIS_SERVER_HOST
      remoteRef:
        key: /affine/AFFINE_REDIS_SERVER_HOST
