apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-data
  namespace: nori-cloud
  labels:
    app: affine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs
  resources:
    requests:
      storage: 10Gi
