apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: to-speckit
  namespace: nori-cloud
  labels:
    app: to-speckit
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`to-speckit.norriswu.me`)
      kind: Rule
      services:
        - name: to-speckit
          port: 3000
