apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guppy-staging-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud-staging
    kind: SecretStore
  target:
    name: guppy-staging-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: GUPPY_*
