apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: nori-cloud
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "searxng-homelab"
      limiter: false
      image_proxy: false
    search:
      formats:
        - html
        - json
