apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: nori-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      initContainers:
        - name: copy-config
          image: busybox
          command: ["sh", "-c", "cp /config/settings.yml /etc/searxng/settings.yml"]
          volumeMounts:
            - name: config-source
              mountPath: /config
            - name: config-writable
              mountPath: /etc/searxng
      containers:
        - name: searxng
          image: searxng/searxng:latest
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_PORT
              value: "8080"
          volumeMounts:
            - name: config-writable
              mountPath: /etc/searxng
      volumes:
        - name: config-source
          configMap:
            name: searxng-config
        - name: config-writable
          emptyDir: {}
