apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: koukou-secret
    namespace: nori-cloud
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: infisical-nori-cloud
        kind: SecretStore
    target:
        name: koukou-secret
        creationPolicy: Owner
    data:
        - secretKey: AUTHENTIK_CLIENT_ID
          remoteRef:
              key: /koukou/AUTHENTIK_CLIENT_ID
        - secretKey: AUTHENTIK_CLIENT_SECRET
          remoteRef:
              key: /koukou/AUTHENTIK_CLIENT_SECRET
        - secretKey: AUTHENTIK_DISCOVERY_URL
          remoteRef:
              key: /koukou/AUTHENTIK_DISCOVERY_URL
        - secretKey: BETTER_AUTH_SECRET
          remoteRef:
              key: /koukou/BETTER_AUTH_SECRET
        - secretKey: BETTER_AUTH_URL
          remoteRef:
              key: /koukou/BETTER_AUTH_URL
        - secretKey: NEXT_PUBLIC_BETTER_AUTH_URL
          remoteRef:
              key: /koukou/NEXT_PUBLIC_BETTER_AUTH_URL
        - secretKey: BOUBOU_URL
          remoteRef:
              key: /koukou/BOUBOU_URL
        - secretKey: DASHSCOPE_API_KEY
          remoteRef:
              key: /koukou/DASHSCOPE_API_KEY
        - secretKey: DEEPSEEK_API_KEY
          remoteRef:
              key: /koukou/DEEPSEEK_API_KEY
