apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nori-butler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nori-butler
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: nori-butler
  labels:
    app: nginx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.norriswu.me`)
      kind: Rule
      services:
        - name: nginx
          port: 80
