apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whisper
  namespace: nori-cloud
spec:
  serviceName: whisper
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: fedirz/faster-whisper-server:latest-cpu
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: WHISPER__MODEL
              value: "Systran/faster-distil-whisper-small.en"
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
  volumeClaimTemplates:
    - metadata:
        name: hf-cache
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: freenas-nfs
        resources:
          requests:
            storage: 10Gi
