---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: infisical-universal-auth
  namespace: nori-lab-dev
spec:
  encryptedData:
    client_id: AgAzSjFPc4jHDS+W3wphqVxR/6JsB+Bali42SSNuMH1fML27JMYCXD1UrtfkMEWvVl72t4GaaYKC45OopI25zA2GIcYvxcu1ituIwHVUIO69F8hoxKY0dK74mjB92ihJZxfMs4zzOqh5ymE+Fo7VfMi95wJqasfV9A/Q+PaPSlpuA04YPNXdibfrg2LadWSkcD50nJp+7bu/AXefrLXaZyzAcNvqCQvQwOIuZYdYyGb6wyZ6TKA3vA2JjB3rusgzxseQwBrbTyttWF3KHDLRmXM5mYtYeBqesofRokdrelSdIAh13TnUtywHt5OkzesRaSu8DpyS5IedWN6ki/n7szaK7HHqB3yGgLhQGeUtH+lHXa9h+h5HXAJ8ez0uSS3h3piatwwxUzTbgYGanMPd94w/R3hqMcp761qaBPvJPQt8eFtYteWRaeotzTEUnT5ED40Eb+ivcw7m0NYpqgnFvkmhJDaytra1g2Sj/A4ILwBPoiIw3SsaHvxYhDqja5Wtm8O4sEA/orZctedsdoYnNUMNdY4OjTvuxyTdSmq9KnE59nkfNnVPtTDnvhYj/WVu0j+AJPM/xdEsDmKfnWMf4yF4fQN2WjY1tKF9zQvAf1ZreSQE8ZL9uk8/ORXB1RMH9Ukzr/YikEBBDcltXP2y5osrPcAoWrE2klztdIGsEtRFd1Hz7VY7xzDETnVpMEaISzzH+N2WsciTmAnQ7IJ3HCEGvYHgjhUcKzCsYJ0t2lz9utV9JAA=
    client_secret: AgBBct4DSEPOnTrxdLEtUYil+Ow3Losj1LdkL6J9CgV9Cx2/tXZNTWQgGFk51NlcBqsktiEq3inU/Rj1znRM7pQ/J5jAUD0AsRtWNNMWkX5uxIj+bH7KRTyD5c1iCCB5S01hU0yZFsK4g3Hedg1DgvyPKdE0C5+UkSNRLKU97rV8vuzn7aaKU1UFKdu3TIC17qJfqQcAUrDP241DB1f3wSHFULmwJ4xZuk0mSneO6lz6N4TT+3FlwKjMOc+NHOM3MWPWKWbEA+CaK0NUQKe4VduXpLmQUjcYWh1pgdyPxw2ljojWXxru4PDlDcBfmGVeDa3tUbSmNthUYUy5GAX4XSAQ7Lv07xW+PaX9OHRGLd57Z5rZ9GAnmIEokxzp81ENuYC9uXSlmZyqhd3BOE8BJR+cSI2VpvDrCR8P0veCv0K2mkpXTT22hkRlQu8jeQvIrCNlk/1aUCGKRblPBFd0rHWojBgASSEW1ux6nkP0oRagFK65JU80jKKWPXFFi8hgHq48EcZoL5hjSekryDlTEbid6t2q084jQRVPkU51IBZ7KODoUJ3KSdAit+MJMb6I5xKtpqzw7jN7yOAw7M+aA3KizeWWA3m3KGbJjVYrI6ivrsOb10kQq3NCkE+lKT0paVMA+1IdYYcuFTSEwQbkQSRNKGYRUIdddH7iGjyO1gz8mW52wJuZqXy4NsalIZAtouoDOPRYLIEaHAgT9v3o4f4ELT8s0DnCF/8cJlvLMjl5YzqC9bbi1XUaUJazFMi8bPoYNqe3wik91M02cQwh9vf0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: infisical-universal-auth
      namespace: nori-lab-dev
