apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nori-lab-dev

resources:
  - ../../base
  - infisical-ua-cred-sealed-secret.yaml

patches:
  - path: secret-store-patch.yaml
