---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: infisical-universal-auth
  namespace: nori-lab-prod
spec:
  encryptedData:
    client_id: AgAgSe3+iS1thcS8K7Datr7AR8uZZHjcy3urnxAsYL/ymTkIJafLflhNlGk/U0DU2i2S6QHdXGtwEc0HBBL1+eieD9cMDHQd0thfu2w6EFAcd2TSqoaFnX6DzRgp7z7JLGgkBudPAclcTU3rgi5CI5MNYs0eugRAcYGzaCu+cY6g5ZEoDzQQKRG6MhEzc3mClM/R/OZ/LBIEH9ZYgOfakADXOhgsTWNhgGt53itnKF5IyuZECZc190bhu+y8KmntVVgfr48uf3aUUMVaMEvGu63jrSkFtl5+KuOcXe07SHUZZ4pYCw5T2lf6s8R6i4UsMknhtkcET4zp2W4ss7Pzp4czIsDVCIx4wqRFuybbcwSYAurKKBKjwQfZxe6eQV7mc0KhgMaeeklSY0UHjaR99kneWIcaoMdvhiPt+NiAIJasSLXUAshOjWagwEYSG1smn9DJQbTzYlla702tTsug13va1GKCEZuKat//FYfduuRnBJbW4AWEwJv/8dvG9KJI4BlWiDoZ8z8OjAIB7p/kGmOLvNNlyVIePUjYyShaUXVGQDYKELxuyb1POzIfp3T0Bf5kAfFdVBx/0cpeWYfsroZmirQmqVNDJAdjPFC48NgdoVYaPGrI2NCAiLGWhEj0d2fH5pEq94yW0iYILSHzwDKljQ8HwzWN28GcgPNvaU3Zx0SlPlopZzgKQf8QKb7dJGazK8Qy1RLhggYkmt4AWd/Oqql2X0jcZSjWmZ9HVo5s7dR90uA=
    client_secret: AgATJxs2CgTstkeLaFykIEegEIekpaxMQoOIa+MIyQN5ve4i+ChERG380St7sRzjs5scKY3ziOOyFW27aq0hkHFdlxlyPiE6Vd/aizqOIQ9GU/dUBjhOY750rJL3Xgl0rYRii4Ub70pg6/QPBth3ro1LQBS8cPw0Ep1iiVr1NH/a42yrnzamvQw2S2dQ3/foS47QoI8gTCNUVuEr0q1Fwz1EqKJDtU86M0NEeB6uvyetcmluDzi1tGs1nj+aLNKVTs4s2uS8a9d2j96NGzDDkQaHejFwBrwA7xI+GAyS13q7vsKaW+mC/zemds8pbHraj1Xcj/eslMWyab2jwkZvnvoiV43Fkfc9x6HWj6LnO4Q0uFdo7r1WoI54RKiz5eNf4XHWKV97Yy0PLLL7YHoVmq43fF3z23mRcwLd6XNnNFe+t1rv0MxhY8LwZ9HZC+z0d2JGFx6fScluZan/iLzX462ZoY9sXlrkJNc69V2C03Rp+a7AQlr7ucckZ9klK0OnUmIL4kA5HXbBXvMd8CBsyC+8Meel9CGvFrBWwJKE/DjSHhsUf2lRwWZVjWSKCs3zz19pk2S63NT/flQT522LqLglnRjR7qklc+JbgwHmmfgUF2rvp7U1mZRkGC+mb2IV4rW5ibusGkInaebd2d2ypv0JaVXhK3z/OuRPfeBT/2pyDX7a2p+Q7hHrAHgR9Foscvmjpac7J4glMEgqUsDGFFGxyUL0SYCF/ZLplXROzFSD2iQTugA0YWla7HH+tBmxDkEMLGRDmzygerAub/jzcMva
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: infisical-universal-auth
      namespace: nori-lab-prod
