global:
    priorityClassName: system-cluster-critical
    envFrom:
        - secretRef:
              name: authentik-credentials

authentik:
    log_level: info
    error_reporting:
        enabled: false

server:
    replicas: 1
    ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
            - authentik.home.norriswu.me
            - auth.home.norriswu.me
            - auth.norriswu.me

worker:
    replicas: 1

# Disable embedded PostgreSQL - using external instance
postgresql:
    enabled: false

redis:
    enabled: true
