apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: /pgadmin/PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: /pgadmin/PGADMIN_DEFAULT_PASSWORD
