apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: nori-cloud
  labels:
    app: pgadmin
  annotations:
    tailscale.com/hostname: pgadmin
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      name: http
