apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-home
  namespace: nori-cloud
  labels:
    app: devbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-opt
  namespace: nori-cloud
  labels:
    app: devbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs
  resources:
    requests:
      storage: 20Gi
