apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: nori-cloud
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs
  resources:
    requests:
      storage: 5Gi
