apiVersion: apps/v1
kind: Deployment
metadata:
  name: guppy
  namespace: nori-cloud
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guppy
  template:
    metadata:
      labels:
        app: guppy
    spec:
      containers:
        - image: ghcr.io/nori-cloud/guppy:sha-fbe0e9f484cf9d2f38eb6295112047ac10a8e718
          name: guppy
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: guppy-secret
