apiVersion: v1
kind: Secret
metadata:
  name: guppy-secret
  namespace: nori-cloud
type: Opaque
stringData:
  DATABASE_URL: "postgresql://username:password@address:port/database"
  BETTER_AUTH_SECRET: "secret"
  BETTER_AUTH_URL: ""
  AUTH_OIDC_ID: ""
  AUTH_OIDC_CLIENT_ID: ""
  AUTH_OIDC_CLIENT_SECRET: ""
  AUTH_OIDC_ISSUER: ""
  STEAM_API_KEY: ""
  UMAMI_URL: ""
  UMAMI_USERNAME: ""
  UMAMI_PASSWORD: ""
  UMAMI_BASE_DOMAIN: ""
