apiVersion: v1
kind: Secret
metadata:
  name: guppy-secret
  namespace: nori-cloud
type: Opaque
stringData:
  DATABASE_URL: ""
  BETTER_AUTH_SECRET: ""
  BETTER_AUTH_URL: ""
  AUTH_OIDC_ID: ""
  AUTH_OIDC_CLIENT_ID: ""
  AUTH_OIDC_CLIENT_SECRET: ""
  AUTH_OIDC_DISCOVERY_URL: ""
  STEAM_API_KEY: ""
  UMAMI_URL: ""
  UMAMI_USERNAME: ""
  UMAMI_PASSWORD: ""
  UMAMI_BASE_DOMAIN: ""
