apiVersion: v1
kind: Secret
metadata:
  name: guppy-secret
  namespace: nori-cloud
type: Opaque
stringData:
  # Required to boot the app
  DATABASE_URL: ""

  # Authentication (NextAuth)
  NEXTAUTH_SECRET: ""

  # OIDC login (all or none required together)
  AUTH_OIDC_ID: ""
  AUTH_OIDC_CLIENT_ID: ""
  AUTH_OIDC_CLIENT_SECRET: ""
  AUTH_OIDC_ISSUER: ""

  # Integrations (optional)
  STEAM_API_KEY: ""
