apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: POSTGRES_DB
