apiVersion: v1
kind: Service
metadata:
  name: postgres-tailscale
  namespace: nori-cloud
  annotations:
    tailscale.com/hostname: postgres
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
