# # prettier-ignore
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: cluster-ingressroute-certificate-staging
#   namespace: {{ .Release.Namespace | quote }}
# spec:
#   secretName: cluster-certificate-secret-staging
#   issuerRef:
#     name: cloudflare-cluster-issuer-staging
#     kind: ClusterIssuer
#   commonName: "*.home.norriswu.me"
#   dnsNames:
#     - "home.norriswu.me"
#     - "*.home.norriswu.me"
---
# prettier-ignore
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ingressroute-certificate
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: cluster-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "norriswu.me"
    - "*.norriswu.me"
    - "pawmery.pet"
    - "*.pawmery.pet"
