# prettier-ignore
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer-staging
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-cluster-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.email }}
            apiTokenSecretRef:
              name: cloudflare-creds
              key: cloudflare_api_token
            selector:
              dnsZones: {{ .Values.dnsZone }}
---
# prettier-ignore
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer-production
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-cluster-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.email }}
            apiTokenSecretRef:
              name: cloudflare-creds
              key: cloudflare_api_token
            selector:
              dnsZones: {{ .Values.dnsZone }}
