apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{\"auths\":{\"https://ghcr.io\":{\"auth\":\"{{ .imagePullSecret | b64enc }}\"}}}"
  data:
    - secretKey: imagePullSecret
      remoteRef:
        key: nori-cloud-ghcr-image-pull-secret
