apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-auth-staging
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: infisical-nori-cloud-staging-auth
  data:
    - secretKey: clientId
      remoteRef:
        key: /nori-cloud/INFISICAL_MI_UA_CLIENT_ID_STAGING
    - secretKey: clientSecret
      remoteRef:
        key: /nori-cloud/INFISICAL_MI_UA_CLIENT_SECRET_STAGING
