# additionalArguments:
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
#  - --certificatesresolvers.cloudflare.acme.email=norris.wu.au@outlook.com
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
#  - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json

# env:
#   - name: CF_DNS_API_TOKEN
#     valueFrom:
#       secretKeyRef:
#         name: cloudflare-creds
#         key: cloudflare_api_token

service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.norriswu.me"

ports:
  web:
    port: 8000
  websecure:
    port: 8443

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
