{{- range .Values.orgs }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  description: "{{ .name }} project"
  sourceRepos:
    - {{ .repoURL }}
  destinations:
    - namespace: {{ .name }}
      server: https://kubernetes.default.svc
      name: in-cluster
---
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default

  source:
    repoURL: {{ .repoURL }}
    targetRevision: HEAD
    path: {{ .appsPath }}

  destination:
    server: https://kubernetes.default.svc
    namespace: system

  syncPolicy:
    automated:
      enable: true
      prune: true
      selfHeal: true
{{- end }}
