apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: infisical-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_CONNECTION_URI
      remoteRef:
        key: /infisical/DB_CONNECTION_URI
    - secretKey: AUTH_SECRET
      remoteRef:
        key: /infisical/AUTH_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: /infisical/ENCRYPTION_KEY
    - secretKey: SMTP_HOST
      remoteRef:
        key: /infisical/SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: /infisical/SMTP_PORT
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: /infisical/SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: /infisical/SMTP_PASSWORD
    - secretKey: SMTP_FROM_ADDRESS
      remoteRef:
        key: /infisical/SMTP_FROM_ADDRESS
