apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
    name: studio-109-prod
    namespace: nori-cloud
spec:
    provider:
        infisical:
            hostAPI: http://infisical.nori-cloud.svc.cluster.local:8080
            auth:
                universalAuthCredentials:
                    clientId:
                        name: infisical-studio-109-auth
                        namespace: nori-cloud
                        key: clientId
                    clientSecret:
                        name: infisical-studio-109-auth
                        namespace: nori-cloud
                        key: clientSecret
            secretsScope:
                projectSlug: studio-109-7vtd
                environmentSlug: prod
                secretsPath: /
                recursive: true
