issuers:
    - name: letsencrypt-cloudflare-staging
      acmeEmail: norris.wu.au@outlook.com
      acmeServer: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
          name: letsencrypt-cloudflare-staging-key
      solvers:
          - dns01:
                cloudflare:
                    email: norris.wu.au@outlook.com
                    apiTokenSecretRef:
                        name: cert-manager-creds
                        key: norriswu_me_cf_dns_token
            selector:
                dnsZones:
                    - norriswu.me
          # - dns01:
          #       cloudflare:
          #           email: Zhugeruntao@gmail.com
          #           apiTokenSecretRef:
          #               name: cert-manager-creds
          #               key: pawmery_pet_cf_dns_token
          #   selector:
          #       dnsZones:
          #           - pawmery.pet
    - name: letsencrypt-cloudflare
      acmeEmail: norris.wu.au@outlook.com
      acmeServer: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
          name: letsencrypt-cloudflare-key
      solvers:
          - dns01:
                cloudflare:
                    email: norris.wu.au@outlook.com
                    apiTokenSecretRef:
                        name: cert-manager-creds
                        key: norriswu_me_cf_dns_token
            selector:
                dnsZones:
                    - norriswu.me
          # - dns01:
          #     cloudflare:
          #       email: Zhugeruntao@gmail.com
          #       apiTokenSecretRef:
          #         name: cert-manager-creds
          #         key: pawmery_pet_cf_dns_token
          #   selector:
          #     dnsZones:
          #       - pawmery.pet

certificates:
    - name: norriswu-me-wildcard
      namespace: networking
      secretName: norriswu-me-wildcard-tls
      issuerRef:
          name: letsencrypt-cloudflare
          kind: ClusterIssuer
      dnsNames:
          - 'norriswu.me'
          - '*.norriswu.me'
