service:
  annotations:
    tailscale.com/hostname: home
  spec:
    loadBalancerClass: tailscale

ports:
  web:
    redirect: websecure
  websecure:
    port: 8443
    tls: {}

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.home.norriswu.me`)
    tls:
      secretName: cluster-certificate-secret

providers:
  kubernetesCRD:
    allowCrossNamespace: true
