apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nori-lab-secret-store
    kind: SecretStore
  target:
    name: cloudflare-credentials
  data:
    - secretKey: token
      remoteRef:
        key: /cloudflare/TUNNEL_TOKEN
