apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nori-lab-tls-issuer
spec:
  acme:
    email: me@norriswu.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: nori-lab-tls-issuer-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
