apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: nori-lab-secret-store
spec:
  provider:
    infisical:
      hostAPI: http://10.0.0.241:8080
      auth:
        universalAuthCredentials:
          clientId:
            name: nori-lab-infisical-auth
            key: clientId
          clientSecret:
            name: nori-lab-infisical-auth
            key: clientSecret
      secretsScope:
        projectSlug: nori-lab-apps
        environmentSlug: prod
        secretsPath: /
        recursive: true
