apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: penpot-secret
    creationPolicy: Owner
  data:
    - secretKey: PENPOT_DATABASE_USERNAME
      remoteRef:
        key: /penpot/PENPOT_DATABASE_USERNAME
    - secretKey: PENPOT_DATABASE_PASSWORD
      remoteRef:
        key: /penpot/PENPOT_DATABASE_PASSWORD
    - secretKey: PENPOT_SECRET_KEY
      remoteRef:
        key: /penpot/PENPOT_SECRET_KEY
