# prettier-ignore
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oauth-client
  namespace: {{ $.Release.Namespace | quote }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  dataFrom:
    - find:
        name:
          regexp: ARGOCD_OAUTH_CLIENT_*
