apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui-helm
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nori-cloud
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com
    targetRevision: 6.11.0
    helm:
      valuesObject:
        ollama:
          enabled: true
        pipelines:
          enabled: false
        persistence:
          enabled: true
          storageClass: freenas-nfs
          size: 10Gi
        ingress:
          enabled: false
        extraEnvVars:
          - name: WEBUI_URL
            value: "https://chat.norriswu.me"
          - name: ENABLE_OAUTH_SIGNUP
            value: "true"
          - name: ENABLE_RAG_WEB_SEARCH
            value: "true"
          - name: RAG_WEB_SEARCH_ENGINE
            value: "searxng"
          - name: RAG_WEB_SEARCH_RESULT_COUNT
            value: "3"
          - name: SEARXNG_QUERY_URL
            value: "http://searxng.nori-cloud.svc.cluster.local:8080/search?q=<query>"
        extraEnvFrom:
          - secretRef:
              name: open-webui-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: nori-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
