apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  target:
    name: open-webui-secret
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /open-webui/OPEN_WEBUI_OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /open-webui/OPEN_WEBUI_OAUTH_CLIENT_SECRET
    - secretKey: OPENID_PROVIDER_URL
      remoteRef:
        key: /open-webui/OPEN_WEBUI_OPENID_PROVIDER_URL
    - secretKey: OAUTH_PROVIDER_NAME
      remoteRef:
        key: /open-webui/OPEN_WEBUI_OAUTH_PROVIDER_NAME
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: /open-webui/OPEN_WEBUI_WEBUI_SECRET_KEY
