apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: nori-cloud
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "searxng-secret-key-change-me"
      limiter: false
      image_proxy: true
    ui:
      static_use_hash: true
    search:
      safe_search: 0
      autocomplete: ""
      default_lang: ""
      formats:
        - html
        - json
    engines:
      - name: google
        engine: google
        shortcut: g
        disabled: false
      - name: duckduckgo
        engine: duckduckgo
        shortcut: ddg
        disabled: false
      - name: wikipedia
        engine: wikipedia
        shortcut: wp
        disabled: false
