apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: disco-panel-secret
  namespace: nori-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-nori-cloud
    kind: SecretStore
  data:
    - secretKey: PLAYIT_SECRET_KEY
      remoteRef:
        key: /disco-panel/PLAYIT_SECRET_KEY
