apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: disco-panel
  namespace: nori-cloud
  labels:
    app: disco-panel
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mc.norriswu.me`)
      kind: Rule
      services:
        - name: disco-panel
          port: 8080
