apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crafty
  namespace: nori-cloud
spec:
  serviceName: crafty
  replicas: 1
  selector:
    matchLabels:
      app: crafty
  template:
    metadata:
      labels:
        app: crafty
    spec:
      containers:
        - name: crafty
          image: arcadiatechnology/crafty-4:latest
          env:
            - name: TZ
              value: Australia/Sydney
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 8123
              name: dynmap
            - containerPort: 19132
              protocol: UDP
              name: bedrock
            - containerPort: 25565
              name: mc-0
            - containerPort: 25566
              name: mc-1
            - containerPort: 25567
              name: mc-2
          volumeMounts:
            - name: crafty-data
              mountPath: /crafty/backups
              subPath: backups
            - name: crafty-data
              mountPath: /crafty/logs
              subPath: logs
            - name: crafty-data
              mountPath: /crafty/servers
              subPath: servers
            - name: crafty-data
              mountPath: /crafty/app/config
              subPath: config
            - name: crafty-data
              mountPath: /crafty/import
              subPath: import
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: crafty-secret
                  key: PLAYIT_SECRET_KEY
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https-playit
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: crafty-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: freenas-nfs
        resources:
          requests:
            storage: 30Gi
