apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: boubou-secret
    namespace: nori-cloud
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: studio-109-prod
        kind: SecretStore
    target:
        name: boubou-secret
        creationPolicy: Owner
    data:
        - secretKey: DATABASE_URL
          remoteRef:
              key: /boubou/DATABASE_URL
        - secretKey: PORT
          remoteRef:
              key: /boubou/PORT
        - secretKey: NODE_ENV
          remoteRef:
              key: /boubou/NODE_ENV
        - secretKey: AWS_S3_BUCKET
          remoteRef:
              key: /boubou/AWS_S3_BUCKET
        - secretKey: AWS_REGION
          remoteRef:
              key: /boubou/AWS_REGION
        - secretKey: AWS_ACCESS_KEY_ID
          remoteRef:
              key: /boubou/AWS_ACCESS_KEY_ID
        - secretKey: AWS_SECRET_ACCESS_KEY
          remoteRef:
              key: /boubou/AWS_SECRET_ACCESS_KEY
