name: Infra Scheduler

on:
  workflow_dispatch:
    inputs:
      action:
        required: true
        type: choice
        default: "plan"
        options:
          - plan
          - apply
          - destroy

env:
  TOFU_VERSION: 1.10.6

defaults:
  run:
    working-directory: ./cloud/digital-ocean

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      summary-encoded: ${{ steps.bootstrap.outputs.summary-encoded }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: OpenTofu Init
        run: tofu init

      - name: Configure Credentials
        env:
          TF_CREDS_BASE64: ${{ secrets.TF_CREDS_BASE64 }}
        run: |
          echo $TF_CREDS_BASE64 | base64 --decode > creds.auto.tfvars

      - name: Bootstrap Infrastructure
        id: bootstrap
        run: |
          ./bootstrap.sh --action ${{ github.event.inputs.action }} > summary.txt
          cat summary.txt
          SUMMARY_ENCODED=$(cat summary.txt | base64 -w 0)
          echo "summary-encoded=$SUMMARY_ENCODED" >> $GITHUB_OUTPUT

  notify:
    if: ${{ always() }}
    needs: [bootstrap]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Send Summary to Discord
        run: |
          MSG="finish with status of ${{ needs.bootstrap.result }}."
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"[Nori-Cloud: Infra Workflow] $MSG meow 🐱\"}" ${{ vars.DISCORD_MESSAGE_WEBHOOK }}
          SUMMARY_ENCODED="${{ needs.bootstrap.outputs.summary-encoded }}"
          SUMMARY=$(echo "$SUMMARY_ENCODED" | base64 --decode)
          echo "Encoded Summary: $SUMMARY_ENCODED"
          echo "Decoded Summary: $SUMMARY"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$SUMMARY\"}" ${{ vars.DISCORD_MESSAGE_WEBHOOK }}
  