name: Infra Scheduler

on:
  workflow_dispatch:
    inputs:
      action:
        required: true
        type: choice
        default: "plan"
        options:
          - plan
          - apply
          - destroy

defaults:
  run:
    working-directory: ./cloud/aws

jobs:
  plan:
    if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.5

      - run: |
          tofu init
          tofu validate
      
      - run: |
          tofu plan -out=plan-${{ github.run_id }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: plan-${{ github.run_id }}
          path: ./cloud/aws/plan-${{ github.run_id }}

  apply:
    needs: plan
    if: github.event.inputs.action == 'apply'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: plan-${{ github.run_id }}
          path: ./cloud/aws
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.5

      - run: |
          tofu init
          echo $GITHUB_WORKSPACE
          echo $(pwd)
          ls -l .
          tofu apply plan-${{ github.run_id }}

  destroy:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.5

      - run: |
          tofu init
          tofu destroy -auto-approve
  
  notify:
    if: ${{ always() }}
    needs: [plan, apply, destroy]
    runs-on: ubuntu-latest
    steps:
      - run: |
          MSG=""
          case "${{ github.event.inputs.action }}" in
            "plan")
              MSG="finish planning with status of ${{ needs.plan.result }}."
              ;;
            "apply")
              MSG="finish applying with status of ${{ needs.apply.result }}."
              ;;
            "destroy")
              MSG="finish destroying with status of ${{ needs.destroy.result }}."
              ;;
          esac
          curl -X POST -H "Content-Type: application/json" -d '{"content": "$MSG meow 🐱"}' ${{ vars.DISCORD_MESSAGE_WEBHOOK }}
  