on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5,6"

jobs:
  shutdown:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud/aws
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.5

      - run: tofu init
      - run: tofu validate
      - run: tofu destroy -auto-approve