on:
  schedule:
    - cron: "0 12 * * 6"
    - cron: "0 12 * * 7"

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: |
          echo "Goodbye, world!"
