apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localai-model-cache
  namespace: nori-cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs
  resources:
    requests:
      storage: 30Gi
